[[data]]
name = "rpi"
hostname = "raspberrypi"
arch = "aarch64-unknown-linux-gnu"
iface = "eth0"
link_rate_mbps = 100.0
mac_address = "b8:27:eb:95:94:78"
supports_power_measurement = true
supports_dpdk_pmd = false
driver_name = "e1000e"

[[data]]
name = "pktgen"
hostname = "gozo"
iface = "eno1"
dpdk_pcie_addr = "0000:00:1f.6"
um24c_addr = "00:BA:55:68:00:19"
pktgen_home = "/home/netlab/gits/Pktgen-DPDK/"
link_rate_mbps = 1000.0
mac_address = "94:c6:91:ac:4b:73"
supports_dpdk_pmd = true
driver_name = "e1000e"

[[data]]
name = "nuc"
hostname = "socorro"
iface = "eno1"
dpdk_pcie_addr = "0000:00:1f.6"
link_rate_mbps = 1000.0
mac_address = "94:c6:91:aa:a0:cb"
supports_dpdk_pmd = true
driver_name = "e1000e"

[[data]]
name = "runner"
hostname = "THE-WAY-OF-ZEN"
